force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Countries from https://countrylayer.com/</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>alpha2Code__c</fullName>
    <label>alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>alpha3Code__c</fullName>
    <label>alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/RegionalBlocs_Acronym__c.field-meta.xml
<CustomField>
    <fullName>RegionalBlocs_Acronym__c</fullName>
    <label>RegionalBlocs Acronym</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>Country_alpha2Code__c</fullName>
    <label>Country alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Country_Capital_City__c</fullName>
    <label>Country Capital City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Region__c.field-meta.xml
<CustomField>
    <fullName>Country_Region__c</fullName>
    <label>Country Region</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_RegionalBlocs_Acronym__c.field-meta.xml
<CustomField>
    <fullName>Country_RegionalBlocs_Acronym__c</fullName>
    <label>Country RegionalBlocs Acronym</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadController.cls
public with sharing class LeadController {
  public static void UpdateCountryFields(List<Lead> leads) {
    Map<String, Country__c> nameCountryMap = new Map<String, Country__c>();
    Set<String> countryNames = new Set<String>();
    for (Lead lead : leads) {
      countryNames.add(lead.Country);
    }
    List<Country__c> countries = [
      SELECT
        Id,
        Alpha2Code__c,
        Alpha3Code__c,
        Capital_City__c,
        Name,
        Region__c,
        RegionalBlocs_Acronym__c
      FROM Country__c
      WHERE Name IN :countryNames
    ];

    for (Country__c country : countries) {
      nameCountryMap.put(country.Name, country);
    }
    for (Lead leadToUpdate : leads) {
      Country__c leadCountry = nameCountryMap.get(leadToUpdate.Country);
      if (leadCountry != null) {
        if (
          leadToUpdate.Country_alpha2Code__c == null ||
          leadCountry.Alpha2Code__c != leadToUpdate.Country_alpha2Code__c
        ) {
          leadToUpdate.Country_alpha2Code__c = leadCountry.Alpha2Code__c;
        }
        if (leadCountry.alpha3Code__c != leadToUpdate.Country_Alpha3Code__c) {
          leadToUpdate.Country_Alpha3Code__c = leadCountry.alpha3Code__c;
        }
        if (
          leadCountry.Capital_City__c != leadToUpdate.Country_Capital_City__c
        ) {
          leadToUpdate.Country_Capital_City__c = leadCountry.Capital_City__c;
        }
        if (leadCountry.Region__c != leadToUpdate.Country_Region__c) {
          leadToUpdate.Country_Region__c = leadCountry.Region__c;
        }
        if (
          leadCountry.RegionalBlocs_Acronym__c !=
          leadToUpdate.Country_RegionalBlocs_Acronym__c
        ) {
          leadToUpdate.Country_RegionalBlocs_Acronym__c = leadCountry.RegionalBlocs_Acronym__c;
        }
      }
    }
  }
}