force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Countries from https://countrylayer.com/</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>alpha2Code__c</fullName>
    <label>alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>alpha3Code__c</fullName>
    <label>alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/RegionalBlocs_Acronym__c.field-meta.xml
<CustomField>
    <fullName>RegionalBlocs_Acronym__c</fullName>
    <label>RegionalBlocs Acronym</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateCountriesBatchTest.cls
@isTest
private class UpdateCountriesBatchTest {
  @testSetup
  static void setup() {
    Country__c country = new Country__c();
    country.Name = 'TestName';
    country.alpha3Code__c = 'TST';
    country.alpha2Code__c = 'TS';
    country.Capital_City__c = 'Testia';
    country.Region__c = 'Testregia';
    insert country;
  }
  @isTest
  static void testBatchExecution() {
    List<CountryDTO> testCountries = new List<CountryDTO>();

    Test.setMock(HttpCalloutMock.class, new CountryApiServiceMock());

    Test.startTest();

    UpdateCountriesBatch batch = new UpdateCountriesBatch();
    Database.executeBatch(batch);
    Test.stopTest();

    List<Country__c> countries = [
      SELECT
        Id,
        Name,
        Alpha3code__c,
        Alpha2code__c,
        Capital_City__c,
        Region__c,
        RegionalBlocs_Acronym__c
      FROM Country__c
    ];

    System.assertEquals('Afghanistan', countries[0].Name);
    System.assertEquals('TST', countries[0].Alpha3code__c);
    System.assertEquals('AF', countries[0].Alpha2code__c);
    System.assertEquals('Kabul', countries[0].Capital_City__c);
    System.assertEquals('SAARC,', countries[0].RegionalBlocs_Acronym__c);
    System.assertEquals('Asia', countries[0].Region__c);
    System.assertEquals(2, countries.size());
  }
}